Update README.md adding the example of usage of -p,--parameter <param-name param-value>
mulesoft-labs/data-weave-cli pull request #54
Opened 2022-10-13 04:08 UTC by julian-miras

2022-10-13 13:10 UTC, machaval approved these changes

2022-10-13 13:19 UTC, machaval commented
The PR is blocked because the commit is not signed. :( . I've created a new PR with just copying this. #55  @julian-miras either feel free to aprove that PR or please create a new one with your commits signed

2022-10-13 19:35 UTC, afelisatti requested changes
Thanks for your contribution, @julian-miras!!! I just added some typing suggestions and simplified the example (turns out we'd been using the more verbose syntax in all examples here, we'll need to change those later).

2022-10-13 19:35 UTC, afelisatti commented on README.md
> +### Using parameters with the map `params`
```suggestion
### Using Parameters
```

2022-10-13 19:35 UTC, afelisatti commented on README.md
> +Using the internal map `params`, we can access to an injected parameter in the command line with the -p option
```suggestion
Using the internal map `params`, we can access injected parameters in the command line with the `-p` option:
```

2022-10-13 19:35 UTC, afelisatti commented on README.md
> +dw -p myName Julian "output applcation/json --- { name : params.myName }"
```suggestion
dw -p myName Julian "output json --- { name : params.myName }"
```

2022-10-14 06:23 UTC, julian-miras commented
Thanks @machaval ! I knew I was something wrong... good learning for my first PR! I will install the GPG keys to sign my commits going forward, and I will use your PR instead of creating a new one. @afelisatti , I will incorporate your suggestions in the #55 so we will be good to go. I will close this one to clean it up. Thanks!

2022-10-14 06:24 UTC, closed without merging